### ISSUE TITLE
possible bug: highlight colors not rendering

### ISSUE THREAD

**Issue by swehba** [chetachiezikeuzor/Highlightr-Plugin#17]
Using either inline or class options does not cause the highlighted text to render in the selected colors. Instead, they continue to render in the dull color used by the theme I'm using — Obsidian Nord. I'm not using any CSS snippets that should interfere.

Here is a paragraph of text with highlightr-inserted codes:

`Lorem ipsum dolor sit amet, consectetur adipiscing elit. <mark style="background: #FF5582A6;">Phasellus nec purus purus. Nunc vel ligula eget dui convallis fermentum</mark> . <mark class="hltr-yellow">Cras elit dolor,</mark> vestibulum id tempus non, interdum sit amet justo. Morbi scelerisque mauris eu metus mattis euismod. Nam pellentesque, elit id semper ornare, ante mauris venenatis est, ac condimentum velit metus et leo. Cras erat ligula, pulvinar vel suscipit vel, tempus at augue. Aenean sem mauris, egestas vitae scelerisque eu, venenatis ac nunc. Mauris quis iaculis velit. Vestibulum feugiat mattis odio et malesuada.`

And here is what it looks like when it renders in Preview mode: [preview](https://cln.sh/aSEKh0+)

I have Live Preview disabled.

**Comment by chetachiezikeuzor** [comment]
I just installed the Obsidian Nord theme and I see that it has some CSS declarations for mark tags:

```css
mark
{
    background-color: var(--text-mark) !important;
}
```

Unfortunately, this theme has the `background-color` property set with `!important` so solving this will be tricky. I would suggest asking the theme developer to remove the `!important`, or you can remove this styling from the theme file itself:

```css
mark
{
    background-color: var(--text-mark);
}
```

Highlightr plugin uses the `background` property intentionally because `background-color` will take precedence. This allows you to reconfigure the highlights if you so choose. But styling them globally with the `mark` tag makes this rather difficult.

**Comment by swehba** [comment]
Brilliant. Thanks. I remove the important directive and all is well.
